name: Reminder to log breakfast calories

on:
  workflow_dispatch:
    
  schedule:
    # Every day at 10 AM Eastern.
    - cron: 0 14 * * *

env:
  USERNAME: ${{ secrets.GMAIL_USERNAME }}
  PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
  HOST: ${{ secrets.GMAIL_HOST }}
  PORT: ${{ secrets.GMAIL_PORT }}
  SECURE: ${{ secrets.GMAIL_SECURE }}
  FROM: ${{ secrets.GMAIL_USERNAME }}
  TO: ${{ secrets.GMAIL_USERNAME }}
  SUBJECT: Log your breakfast calories!
  TEXT: |
    - Logging isn't just a routine task!
    - Do you want to get healthy or not?

jobs:
  remind:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm ci
      
      - name: Send me an email
        run: npx ts-node src/send-email.ts

      - name: Send me a text
        env:
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        run: npx ts-node src/send-tmobile-sms.ts
