name: Upon Waking | Drink water

on:
  workflow_dispatch:

  schedule:
    # Every day at 11:35 AM Eastern
    - cron: 35 15 * * *

env:
  USERNAME: ${{ secrets.GMAIL_USERNAME }}
  PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
  HOST: ${{ secrets.GMAIL_HOST }}
  PORT: ${{ secrets.GMAIL_PORT }}
  SECURE: ${{ secrets.GMAIL_SECURE }}
  FROM: ${{ secrets.GMAIL_USERNAME }}
  TO: ${{ secrets.GMAIL_USERNAME }}
  SUBJECT: Drink 32 fl oz of water!
  TEXT: |
    - Fill up 32 fl oz of water!
    - Drink water!
    - Water is essential for kidney health!
    - Water will help you lose weight!
    - Water keeps you feeling fuller longer!

jobs:
  remind:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm ci
      
      - name: Send me an email
        run: npx ts-node src/send-email.ts

      - name: Send me a text
        env:
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        run: npx ts-node src/send-tmobile-sms.ts