name: Why am I doing this?

on:
  workflow_dispatch:
    
  schedule:
    # Every day at 8 AM Eastern.
    - cron: 0 12 * * *

env:
  USERNAME: ${{ secrets.GMAIL_USERNAME }}
  PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
  HOST: ${{ secrets.GMAIl_HOST }}
  PORT: ${{ secrets.GMAIL_PORT }}
  SECURE: ${{ secrets.GMAIL_SECURE }}
  FROM: ${{ secrets.GMAIL_USERNAME }}
  TO: ${{ secrets.GMAIL_USERNAME }}
  SUBJECT: Do you remember why you're doing this?
  TEXT: |
    - Do this for God!
    - Do this for your kids!
    - Do this for your wife!
    - Do this for your body!
    - You have to be there for your family!
    - You have to get off your BP meds!
    - You want to look good!
    - You CAN DO THIS!

jobs:
  tell-me-why:
    
    runs-on: ubuntu-latest

    steps:
      - name: npm install
        run: npm ci
      
      - name: Send me an email
        run: npx ts-node src/send-email.ts
